<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ThronefallTrainer</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="AstarPathfindingProject" />
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.PhysicsModule" />
    <Reference Include="0Harmony" />
    <Reference Include="UnityEngine.IMGUIModule" />
    <Reference Include="BepInEx" />
    <Reference Include="KB.FogRTS.Runtime" />
    <Reference Include="UnityEngine.ScreenCaptureModule" />
    <Reference Include="UnityEngine.ImageConversionModule" />
    <Reference Include="UnityEngine.InputLegacyModule" />
    <Reference Include="UnityEngine.TextRenderingModule" />
  </ItemGroup>
</Project>