# gen-fields.ps1 — generate the shared SnapshotData field reference.
# The policy validator (C# reflection), the replay harness, and the future
# Python sidecar all need the same field list. Source of truth = the struct
# definition in src/BotBrain.cs. Emits:
#   docs/SNAPSHOT-FIELDS.md   (human table)
#   agent/snapshot-fields.json (machine form for the sidecar/validator)
#
# Usage: .\tools\gen-fields.ps1

param([string]$GameRoot = (Split-Path $PSScriptRoot -Parent | Split-Path -Parent))
$ErrorActionPreference = 'Stop'   # param must be the first statement — the
                                  # old order was a parse error (script dead)
$src    = Join-Path $PSScriptRoot '..\src\BotBrain.cs'
$docOut = Join-Path $PSScriptRoot '..\docs\SNAPSHOT-FIELDS.md'
# GameRoot-parametrized — the hardcoded '..\..\Thronefall' broke under any
# repo rename (audit: inconsistent with every other tool's layout param).
$jsonOut = Join-Path $GameRoot 'BepInEx\plugins\agent\snapshot-fields.json'

$code = Get-Content $src -Raw
$body = [regex]::Match($code, '(?s)internal struct SnapshotData\s*\{(.*?)\n    \}').Groups[1].Value
if ($body.Length -eq 0) { Write-Error 'SnapshotData struct not found in BotBrain.cs'; exit 1 }

$fields = @()
$comment = ''
foreach ($line in ($body -split "`n")) {
    $t = $line.Trim()
    if ($t -match '^//\s*(.*)$') { $comment = $Matches[1]; continue }
    if ($t -match '^public\s+(\w+)\s+(\w+);') {
        $fields += [pscustomobject]@{ name = $Matches[2]; type = $Matches[1]; comment = $comment }
        $comment = ''
    }
    elseif ($t -notmatch '^\s*$' -and $t -notmatch '^//') { $comment = '' }
}

$md = @()
$md += '# SnapshotData fields (generated by tools/gen-fields.ps1 — do not edit)'
$md += ''
$md += 'Policy rules (`agent/policy.txt`) may test any of these fields with ops `> >= < <= == !=`.'
$md += 'Vec2 values are world-space [x,z] pairs.'
$md += ''
$md += '| Field | Type | Note |'
$md += '|---|---|---|'
foreach ($f in $fields) { $md += "| $($f.name) | $($f.type) | $($f.comment) |" }
$md -join "`n" | Set-Content -Path $docOut -Encoding UTF8

$json = @{ fields = @($fields | ForEach-Object { @{ n = $_.name; t = $_.type; d = $_.comment } }) }
New-Item -ItemType Directory -Path (Split-Path $jsonOut) -Force | Out-Null
# UTF8 without BOM — PS 5.1 -Encoding UTF8 writes a BOM that breaks strict
# Python json.loads() consumers of the sidecar file.
[IO.File]::WriteAllText($jsonOut, ($json | ConvertTo-Json -Depth 4 -Compress))

Write-Host "gen-fields: $($fields.Count) fields -> $docOut + $jsonOut"
